version: 2.1

jobs:
  build:
    parameters:
      node-options-envvar:
        type: string
        default: ''
    docker:
      - image: cimg/node:18.18.1
    environment:
      NODE_OPTIONS: '<< parameters.node-options-envvar >>'
    resource_class: large
    steps:
      - run: |
          printenv NODE_OPTIONS
      - run:
          name: Check memory available in Node
          command: |
            node -e 'console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024*1024))'

workflows:
  main:
    jobs:
      - build:
          matrix:
            parameters:
              node-options-envvar:
                - '--max-old-space-size=4096'
                - '--max_old_space_size=1024'
